### ISSUE TITLE
Persistent Failures on seemingly random CR episodes. 

### ISSUE THREAD

**Issue by powkhenai** [animeloyalty/animesync#37]
I'm getting the following stack trace consistently on individual episodes of some shows: 

```
Error: FetchError: request to https://ll.v.vrv.co/evs1/396e4809dafe8f456778c66fcb6d8cda/assets/b47fc899136c83c5973b3c0df6db2580_3884906.mp4/encryption.key?t=exp=1622599139~acl=/evs1/396e4809dafe8f456778c66fcb6d8cda/assets/b47fc899136c83c5973b3c0df6db2580_3884906.mp4/*~hmac=790c57d505d0a58c6eba9b66ff2bf7644a6fc045d2a3f39f415f3b68937a78c3 failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/animesync/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:376:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

The above is an excerpt from running the command: 

`animesync download https://www.crunchyroll.com/jujutsu-kaisen`

all of the other output is just episodes and time to download them.
I'm not behind a proxy or a vpn or anything, I should be pretty straight forward traffic, any thoughts?

**Comment by Deathspike** [comment]
That is odd. Could you tell me the operating system you're running on, and attach your full log?
They're in `~/animesync/logger` (linux, mac) or `%HOMEDIR%\animesync\logger` (windows).

**Comment by powkhenai** [comment]
I'm on Fedora 33
`Linux dark-matter 5.12.7-200.fc33.x86_64 #1 SMP Wed May 26 13:15:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
[2021-05-30.log](https://github.com/animeloyalty/animesync/files/6571497/2021-05-30.log)

I'm happy to help out in any way I can, let me know if I can run tests, or try to reproduce further. I'm plenty comfortable pulling dev branches to test against and the like.

**Comment by Deathspike** [comment]
This one is pretty darn weird. This is one of the example I've found in the logging:

```
[2021-05-30T17:45:43.737Z] DEBUG [hls @ 0x5631abb02340] Opening 'http://localhost:6583/api/rewrite/https%3A%2F%2Fll.v.vrv.co%2Fevs1%2F396e4809dafe8f456778c66fcb6d8cda%2Fassets%2Fb47fc899136c83c5973b3c0df6db2580_3884906.mp4%2Fencryption.key%3Ft%3Dexp%3D1622569544~acl%3D%2Fevs1%2F396e4809dafe8f456778c66fcb6d8cda%2Fassets%2Fb47fc899136c83c5973b3c0df6db2580_3884906.mp4%2F*~hmac%3Db39b9b582f15d486f1de96e1c4deac0621082978ec4383ae0b8660acad40f08d?user-agent=Mozilla%2F5.0%20(X11%3B%20Linux%20x86_64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F91.0.4472.77%20Safari%2F537.36&origin=https%3A%2F%2Fstatic.crunchyroll.com&referer=https%3A%2F%2Fstatic.crunchyroll.com%2F' for reading
[2021-05-30T17:45:43.809Z] DEBUG HTTP/1.1 500 {"statusCode":500,"message":"FetchError: request to https://ll.v.vrv.co/evs1/396e4809dafe8f456778c66fcb6d8cda/assets/b47fc899136c83c5973b3c0df6db2580_3884906.mp4/encryption.key?t=exp=1622569544~acl=/evs1/396e4809dafe8f456778c66fcb6d8cda/assets/b47fc899136c83c5973b3c0df6db2580_3884906.mp4/*~hmac=b39b9b582f15d486f1de96e1c4deac0621082978ec4383ae0b8660acad40f08d failed, reason: Client network socket disconnected before secure TLS connection was established\n    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/animesync/node_modules/node-fetch/lib/index.js:1461:11)\n    at ClientRequest.emit (events.js:376:20)\n    at TLSSocket.socketErrorListener (_http_client.js:475:9)\n    at TLSSocket.emit (events.js:376:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"}
```

It pipes the request through the emulation layer, and it just gives up in ~700ms.  Seeing that #30 is essentially the exact opposite (request never gives up even though it should) I think there is something odd in the HTTP emulation or socket forwarder. I'll have to dive deeper into. Will keep you in the loop as I progress.

**Comment by Deathspike** [comment]
I've just published a *beta* version (0.11.11-beta.0). Install with:
`npm install -g animesync@beta`
Could you test this version? I've improved piece handling w/ retries.

**Comment by powkhenai** [comment]
I'll test it as soon as I get out of work this afternoon. Thanks for the quick turn-around on this!

**Comment by powkhenai** [comment]
Seems like no glory on this one... 
```
(0)-(22:06:18)-> animesync --version
0.11.1-1.beta.0

(0)-(22:07:33)-> cd library/.animesync/JUJUTSU\ KAISEN

(0)-(22:07:38)-> rm JUJUTSU\ KAISEN\ 04\ \[Crunchyroll\] 

(0)-(22:07:46)-> animesync download https://www.crunchyroll.com/jujutsu-kaisen
Starting http://localhost:6583/
Sourcing /home/jake/animesync/library
Fetching https://www.crunchyroll.com/jujutsu-kaisen
Skipping JUJUTSU KAISEN 01 [Crunchyroll]
Skipping JUJUTSU KAISEN 02 [Crunchyroll]
Skipping JUJUTSU KAISEN 03 [Crunchyroll]
Fetching JUJUTSU KAISEN 04 [Crunchyroll]
Error: FetchError: request to https://ll.v.vrv.co/evs1/396e4809dafe8f456778c66fcb6d8cda/assets/b47fc899136c83c5973b3c0df6db2580_3884906.mp4/encryption.key?t=exp=1622858872~acl=/evs1/396e4809dafe8f456778c66fcb6d8cda/assets/b47fc899136c83c5973b3c0df6db2580_3884906.mp4/*~hmac=ab2c8f06aa713282775cb3e87201c178914efe94e71bf0a17da3c8815d32d240 failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/animesync/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:376:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
[2021-06-02.log](https://github.com/animeloyalty/animesync/files/6588472/2021-06-02.log)

**Comment by Deathspike** [comment]
Is this the correct log? Logging doesn't show a failure on `JUJUTSU KAISEN 04 [Crunchyroll]`.
It would be a little confusing though, as the error that is shown in the console is caught and re-attempted.
The end result should always be a `Finished` or `Rejected` for the episode.

**Comment by powkhenai** [comment]
Wow, this is totally my bad, I saw the error there on the CLI and assumed I was seeing the same issue. But actually taking the 10 seconds to look, there is definitely a file there, and it is definitely episode 4. So that was just bad due diligence on my end, sorry about that. (I don't know if it's notable, but that file is weirdly like twice as large as the others in the show)

Point is, seems like you got it, thanks again for the quick turn-around and sorry for the false negative.

**Comment by Deathspike** [comment]
Well, I'm glad it did succeed!

There are issues with this approach for sure. I didn't realize the changed file size; that's a big one.
Another one is the performance; it's super slow and consumes tons of memory.

But at least I know I'm thinking in the right direction.
I'll change some things and let you test again. To be continued :-)

**Comment by powkhenai** [comment]
Yeah! Definitely heading in the right direction, keep me posted here and I'll keep testing as long as I can reproduce the issue. Happy to help out! (Thanks for the great app btw, sorry I didn't lead with that, sometimes work brain makes me less friendly in public than I should be)

Yeah, for current use I'll prefer the release copy over the beta where possible. Thanks for the advice.

**Comment by Deathspike** [comment]
No worries about that!

I've figured that the release version had the same issue; video/audio was downloading in duplicate since I made a change to support external audio streams as Funimation has been doing for their latest releases (different audio streams with the same video stream, probably to reduce data stored on their servers). So I've fixed that version, and pushed a new beta, too.

You should get proper files with this new beta, but performance might leave something to be desired still.
I'll work on that later. I'll keep you in the loop!

**Comment by Deathspike** [comment]
This improvement is now live in `0.11.12`.

**Comment by powkhenai** [comment]
Thanks for all the work on this, I appreciate it!
